### PR TITLE
Feature springboot update

### PR DESCRIPTION
**Pull request by friederici**
( Retry for https://github.com/CommonWorkflowScheduler/KubernetesScheduler/pull/5 )

This will update the Spring Boot Version to 3.1.5 and fixes some inconsistencies in the buildfile.

    Due to the inheritance of Spring Boot, it is required to overwrite some of the fields explicit (see https://maven.apache.org/pom.html#More_Project_Information )

    javax.annotation.PostConstruct has been renamed to jakarta.annotation.PostConstruct

    Some of the dependencies are actually not needed, because spring-boot-starters do pull in those as dependencies. The cleanup should be done in a second sweep (not included here).

    The explicit version statements for some dependencies have been removed, leading to fhe following changes:

           <groupId>org.projectlombok</groupId>
           <artifactId>lombok</artifactId>
           <version>1.18.26</version> -> managed: 1.18.30

           <groupId>junit</groupId>
           <artifactId>junit</artifactId>
           <version>4.13.2</version> -> managed: 4.13.2

           <groupId>org.springframework.boot</groupId>
           <artifactId>spring-boot-starter-web</artifactId>
           <version>3.0.4</version> -> managed: 3.1.5

           <groupId>org.springframework.boot</groupId>
           <artifactId>spring-boot-starter-test</artifactId>
           <version>3.0.4</version> -> managed: 3.1.5

           <groupId>org.junit.vintage</groupId>
           <artifactId>junit-vintage-engine</artifactId>
          <version>5.9.2</version> -> managed: 4.13.2

           <groupId>ch.qos.logback</groupId>
           <artifactId>logback-core</artifactId>
           <version>1.4.6</version> -> managed: 1.4.11

           <groupId>com.fasterxml.jackson.core</groupId>
           <artifactId>jackson-databind</artifactId>
           <version>2.14.2</version> -> managed: 2.15.3

           <groupId>com.fasterxml.jackson.core</groupId>
           <artifactId>jackson-core</artifactId>
           <version>2.15.0-rc2</version> -> managed: 2.15.3

           <groupId>com.fasterxml.jackson.core</groupId>
           <artifactId>jackson-annotations</artifactId>
           <version>2.15.0-rc2</version> -> managed: 2.15.3

               <groupId>org.apache.maven.plugins</groupId>
               <artifactId>maven-surefire-plugin</artifactId>
               <version>3.0.0-M5</version> -> managed: 3.0.0

### CODE REVIEW

**Comment by friederici** [comment]
It appears that I've missed that Spring Boot 3.0+ requires Java 17:
https://docs.spring.io/spring-boot/docs/3.0.x/reference/html/getting-started.html#getting-started.system-requirements

My Spring Tool Suite 4 includes an own runtime, this is why I did not recognized it locally.

**Comment by Lehmann-Fabian** [comment]
In this case you also need to update the Dockerfile!

**Comment by Lehmann-Fabian** [comment]
Thank you. I will merge this, but please confirm that you can run a workflow using the new Dockerbuild.

**Comment by friederici** [comment]
From https://spring.io/projects/spring-boot#support 

The last 2.7.x branch will reach end of OSS support in 22 days. Looks like 3.x + is the only way forward, but this comes with the Java 17 requirement attached.

There is no urgend need for this move from my point of view, but it must be done someday anyway 🤷

**Comment by Lehmann-Fabian** [comment]
Oh, I fully agree. We should move to Java 17; I even thought about going directly to Java 21.
I just wanted your confirmation that there is no problem running a test workflow with the new build.
Otherwise, we have to address this first.

**Comment by friederici** [comment]
> Thank you. I will merge this, but please confirm that you can run a workflow using the new Dockerbuild.

I'll try this and come back to you when I'm sure it works.

**Comment by Lehmann-Fabian** [comment]
Thank you.

**Comment by friederici** [comment]
Ok, that was more difficult than expected. I've ironed out the problems that arose due to the spring boot 2 -> 3 update.

I can confirm that my synthetic workflows run locally and from docker container ( see friederici/cws:latest )

There were some hidden problems, e.g. the openapi functionality. So I cannot guarantee that there might be some part that is still not ok somewhere.

Do you have the chance to test this before merging?

**Comment by Lehmann-Fabian** [comment]
Great work, thank you.
As one workflow runs, communication seems to work. 
These were the problems I faced when updating the versions, and I wanted you to check.

**Review by Lehmann-Fabian — APPROVED** [review]

**Comment by Lehmann-Fabian** [comment]
Can you please sign your commits, so I can merge this.
(Last time you did)

**Comment by friederici** [comment]
> Great work, thank you. As one workflow runs, communication seems to work. These were the problems I faced when updating the versions, and I wanted you to check.

The cause for this is:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes

PathPattern Based Path Matching Strategy for Spring MVC

This is the change in the application.yml

**Comment by Lehmann-Fabian** [comment]
I see. We have to test the SWAGGER and API Docs.
We should also try without the adapted application.yml to directly switch to the new PathPattern.
I can do this, but this will take some time.

**Comment by friederici** [comment]
> We should also try without the adapted application.yml to directly switch to the new PathPattern.

nf-cws creates a double / after v1, the old matcher was more generous

> I can do this, but this will take some time.

I don't need the changes for my work, so there is no pressure

**Pull request closed without merging**
