### PR TITLE
update spring boot version to 3.1.5

### PR DESCRIPTION
**Pull request by friederici**
This will update the Spring Boot Version to 3.1.5 and fixes some inconsistencies in the buildfile.

- Due to the inheritance of Spring Boot, it is required to overwrite some of the fields explicit (see https://maven.apache.org/pom.html#More_Project_Information )
- javax.annotation.PostConstruct has been renamed to jakarta.annotation.PostConstruct
- Some of the dependencies are actually not needed, because spring-boot-starters do pull in those as dependencies. The cleanup should be done in a second sweep (not included here).
- The explicit version statements for some dependencies have been removed, leading to fhe following changes:

             <groupId>org.projectlombok</groupId>
             <artifactId>lombok</artifactId>
             <version>1.18.26</version> -> managed: 1.18.30

             <groupId>junit</groupId>
             <artifactId>junit</artifactId>
             <version>4.13.2</version> -> managed: 4.13.2

             <groupId>org.springframework.boot</groupId>
             <artifactId>spring-boot-starter-web</artifactId>
             <version>3.0.4</version> -> managed: 3.1.5

             <groupId>org.springframework.boot</groupId>
             <artifactId>spring-boot-starter-test</artifactId>
             <version>3.0.4</version> -> managed: 3.1.5

             <groupId>org.junit.vintage</groupId>
             <artifactId>junit-vintage-engine</artifactId>
            <version>5.9.2</version> -> managed: 4.13.2

             <groupId>ch.qos.logback</groupId>
             <artifactId>logback-core</artifactId>
             <version>1.4.6</version> -> managed: 1.4.11

             <groupId>com.fasterxml.jackson.core</groupId>
             <artifactId>jackson-databind</artifactId>
             <version>2.14.2</version> -> managed: 2.15.3

             <groupId>com.fasterxml.jackson.core</groupId>
             <artifactId>jackson-core</artifactId>
             <version>2.15.0-rc2</version> -> managed: 2.15.3

             <groupId>com.fasterxml.jackson.core</groupId>
             <artifactId>jackson-annotations</artifactId>
             <version>2.15.0-rc2</version> -> managed: 2.15.3

                 <groupId>org.apache.maven.plugins</groupId>
                 <artifactId>maven-surefire-plugin</artifactId>
                 <version>3.0.0-M5</version> -> managed: 3.0.0

### CODE REVIEW

**Comment by friederici** [comment]
Note: This dependencies are not needed explicitly in the pom.xml:

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-inline</artifactId>
            <version>5.2.0</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>

**Comment by Lehmann-Fabian** [comment]
Thank you.
Can you please fix the build error, the CI pipeline crashed.

**Comment by Lehmann-Fabian** [comment]
I reverted this commit and activated tests for PRs (hopefully).
Can you please recreate this PR, so it is tested before I merge it?
Sorry for the circumstances!

**Comment by Lehmann-Fabian** [comment]
Maybe it is enough if you comment on this PR
https://stackoverflow.com/a/13383299

**Pull request merged**
